### PR TITLE
Allow compilation on android.

### PR DESCRIPTION
**Pull request by metajack**
Sad face.

### CODE REVIEW

**Comment by mbrubeck** [comment]
How about something like this, which I think would be less likely to break when adding new items:

``` rust
#![feature(globs)]
pub use inner::*;

#[cfg(not(target_os="android"))]
mod inner {
/* CODE GOES HERE */
}
#[cfg(target_os="android")]
mod inner {}
```

**Comment by metajack** [comment]
Let me see if I can get that to work. I'm slightly concerned about making upstream merges difficult.

@bjz would you accept an upstream change to make this work?

**Comment by mbrubeck** [comment]
Eh, I'm fine with the original PR here if there isn't a much simpler alternative, especially since it should be temporary (just until Cargo supports conditional dependencies).

**Comment by brendanzab** [comment]
Yeek what?

**Comment by brendanzab** [comment]
Does glfw support android now?

**Comment by metajack** [comment]
@bjz no, but cargo doesn't support conditional dependencies yet, so we have to make glfw-rs compile on android by ifdefing out the entire crate.

Looks like @alexcrichton has almost landed features in cargo now, so don't worry about this.

**Comment by brendanzab** [comment]
Oh ok, cool.

**Pull request merged**
