### PR TITLE
Add a binding for `glfwPostEmptyEvent()`

### PR DESCRIPTION
**Pull request by pcwalton**
r? @larsbergstrom

### CODE REVIEW

**Comment by metajack** [comment]
This should be submitted upstream.

**Comment by pcwalton** [comment]
@metajack This symbol is only present on pre-release versions of GLFW, so submitting it upstream would break all stable releases of GLFW.

**Comment by metajack** [comment]
I'm not super thrilled about digging farther into this fork. Hopefully this will unwind itself soon.

**Comment by brendanzab** [comment]
We are having trouble with `-fPIC` on glfw (bjz/glfw-rs#239) but I'm pretty sure it is fixed on the master branch of glfw. Perhaps we should just migrate to using the latest glfw version until 3.1 is released?

**Comment by larsbergstrom** [comment]
@metajack Presumably once we switch to glutin we'll replace not only GLUT but also GLFW and be free of it. Though that's one of the topics for the workweek next week!

**Comment by brendanzab** [comment]
Yeah, glutin would be great. glfw-rs won't be needed forever, thankfully :)

**Pull request merged**
