### PR TITLE
Use `c_char` for C strings (instead of `i8`)

### PR DESCRIPTION
**Pull request by akosthekiss**
Also, add `#[cfg(not(target_os="android"))]` to two recently added functions

### CODE REVIEW

**Comment by brendanzab** [comment]
Will this be upstreamed? :3

**Comment by akosthekiss** [comment]
I almost did and then realized that https://github.com/servo/glfw-rs/tree/rustup_20150109 is 70+ commits ahead of https://github.com/bjz/glfw-rs , and those parts of the code that get fixed here (those working with `i8`) are not existing upstream (yet?). I'm not sure who is to do all the upstreaming?

**Comment by brendanzab** [comment]
waaahhhh! 70 commits!

**Comment by brendanzab** [comment]
Seems like the servo fork [is being kept up to date](https://github.com/bjz/glfw-rs/network) - could you submit PRs to the bjz/glfw-rs repo in future?

**Comment by akosthekiss** [comment]
Must be my bad then. Sorry. I didn't want to push blame on anyone. I must have been deceived by github (which still shows to me: "This branch is 74 commits ahead, 7 commits behind bjz:master"; not sure why...) I'll submit the PR asap.

**Comment by brendanzab** [comment]
No worries, no stress!

**Pull request merged**
